language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
notifications:
  slack: teamcarnell:zhTADgjsb7yJ5RPEd7LPNFwI
  email:
    - carnell28@gmail.com
  on_success: always
  on_failure: always
env:
  global:
    - secure: Yrg1adV2irhJnaHhXf8vhR+ExQ2I2pRGqqD4oGK7MnFAklEDROTXHF10VnW9rIMCy3Qw17QUgiBZAXMzDoKn3dRvMHchSG54pRJ6E3UEZVu/Lh/dqu0gSf//rLYpEmoyD1RTU6gwdZx7V29yE1GaAmtK6D4d9EgaM9+UTgO4JdlnHGQm7dAvcgF8H+p/K4G99GVSLPBuIZbA2zBCvNq59AMlJdMUuyKJrKVH9M06Dh1EFETzsvUBHDHsk9fLgUN7kGlZ6mESSmBccNfjOPyqNDkVB40P3mFd5wkHVFdt4MLME01H5xcpRiuFecGntTYi4qKgVAdIpbo7zh0SJS6vcwsflhtNMJkK/M0FIJ7xNYscLvTpWJTNIpTJI6XCn+GAACJ98q0YvvhVOBsUXch7vjWsmJY5yj0DEHWVcLIRg4tdY6Xrrj1vUs3iZMMLoUkVk/fZp0r7irUSAOfWK4++SS4dc68KR9qoTFsEr/HOZc9w/kBqvdRaMoQNmGwOtR5686ari3+SjX0lBfoCrF+Jn4XtNXIEU4c8kP9PeLrEtOOXY8cUkeg60ugaBpXKMRyuxs04QBbrkl9xIlV0sNxi+vQyi7PpnaFWtSkM6kAtTZ1Qoh2R+cwOvo2r4cRe4LvLtZYdvn6cHG9pf+kzWayDKzGoflB1NL3zMcjO7GT1P3s=
    - secure: j/iVN/4htMchxyS6V+qCHwVS+N04g2uTVJp1B58X77REhgrI/wY3bAaZRSUF4c5fj6npj4U6zalN79nSlaYSUsg2tGkX3iSkggRyqjf7/K7ZfL+H+ZBtD9sBXEmrsE9ehctQIOMmS47eXo2fd1+yUjZnLcfyhkQqYtZfskpQ9IQIWNI7/edkY3zWvX/Tto/yPpcr7DdEdu4S6RUvQaVO67b+0VQ0+BJmE/cFgDxSgWifv91510TEn77b1eOc0P5C0mfmh/R+A/3OaNtCGu6adrumxKdEV5n4VwWqe6OdNwmszi1oS/RUrxuhm2SLrvNzbqIjD4Oi62CXeLUVhIKBVKM1DBcgaU4a+5/vq9+/qw9bPvlhen1J0ODlkDStu++ycGoR6NPuBDnLLIQqf4TevlQVvkHe0hhaK16AoPJlLDjTEglyjrv/dEA2e/v+GzA/2oKF+DPs9Z35D1SvID7FOIHthnuSI2MHv1BGQRLJbRqo7FnSOiJoPmzqVfrU1ovNZyM2EJVcc+E1B/uP1bYXAIVRX9m2/qQh+Ch4tcR1qTJcQKDChhUdAyhNG6ExLtsBOGiwyoikZ5jbIg7K2atJvyQVbG3cTIPpi6vD790rdJU2m1OOZ3ncy0ZzRKPemckNmpvBPH6kfzd9T2Td8uQU496WLftKZerP05ddR30pIrU=
    - secure: K3qdAHF0ju54ZQqKoRohqkyZLfkdOg2EAq7NtLBLLuFrX+J6ZUORoQhP/SzaNfVfCjRKOmBvSMc7y9kk3YFl2qhYvVg8gI5gWREsDUHchjLGI13PGGI3ncHjYHw03byqOqysf2HfHE4/2TZ+HZgtPrfa9txNIZuz59weN3CCEQ1+4jGOKZCTJr5WDKJZNqq7GQH3pdqP54jEYT1iJqQqwjxhuAy5vpZJmP0RpyOA/McdA4u6gbnGOiuphs5OdF5LGmba0HyI+gNIrDK94mHSPhjhaLpfxhCxA8oFEy7Ylot0W2CBgFeBYZHSxMNnmpf4W/D3pKQlfJgJmPhm27IBkJP8UhAr9YPiPWqvXG/WJk14FMA0ZV+38kRylT/nIt344BLmvMFVuz5WDaJSaZaY9fgNDnqkB6cVJZF5FpZnBynzIOZVvMFLDJuR+4xDEIk7SYX8PDrehQaTSHzCdZNON6fRLikOdTCudOAMvavoCWwNniWctM4j/a9A/mmhR3vWh7igLXngJWVYROethIW6/CATPAkaAXxNGDENABNbmm75AjLVGMoF1D6YIhQsOIpSS1aDoWPQuQzh/cGG+TaMjavPGjP+YSzFPHNHe7SpkxrKPBwPD9iNS8yjlS7SKnFi9sUu3U3ukWtYOE2ctxCdNgRR8rUPziRs9YluzZUa1w8=
  matrix:
    - TEST_DIR=chapter1-code
script:
  - mvn clean package
